# TODO implement the kubernetes manifest here
apiVersion: apps/v1
kind: Deployment
metadata:
  name: BotApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BotApp
  template:
    metadata:
      labels:
        app: BotApp
    spec:
      containers:
      - name: BotApp
        image:
        ports:
        - containerPort: 80